name: build-iso
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build iso
    - run: cp result/iso/*.iso nickos.iso
    - uses: actions/upload-artifact@v3
      with:
        name: nickos-iso
        path: nickos.iso
