name: release
on:
  push:
    tags: '*'
jobs:
  build:
    uses: ./.github/workflows/build-iso.yml
  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: nickos-iso
      - run: ls -R
      - run: echo ${{ steps.download.output.download-path }}
      - run: ls -l ${{ steps.download.output.download-path }}
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.download.output.download-path }}
